# Generated by Django 5.0.1 on 2024-02-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0002_faq"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lawer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("Contactno", models.IntegerField(max_length=30)),
                ("Address", models.CharField(max_length=30)),
                ("Firm", models.CharField(max_length=30)),
                ("Image", models.ImageField(blank=True, upload_to="data")),
                ("Experience", models.CharField(max_length=30)),
                ("Info", models.CharField(max_length=30)),
                ("Emailid", models.EmailField(max_length=30)),
                ("Map", models.CharField(max_length=30)),
            ],
        ),
    ]
