# Generated by Django 5.0.1 on 2024-02-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0003_lawer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=30)),
                ("Image", models.ImageField(blank=True, upload_to="data")),
                ("Content", models.TextField()),
                ("Post_date", models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="HelpLINENO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("State", models.CharField(max_length=30)),
                ("Number", models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Laws",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Law_category", models.CharField(max_length=30)),
                ("Name", models.CharField(max_length=30)),
                ("Description", models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="NGOS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("Contactno", models.IntegerField(max_length=30)),
                ("Address", models.CharField(max_length=30)),
                ("Slogen", models.CharField(max_length=30)),
                ("Image", models.ImageField(blank=True, upload_to="data")),
                ("Website", models.CharField(max_length=30)),
                ("Info", models.CharField(max_length=30)),
                ("Emailid", models.EmailField(max_length=30)),
                ("Map", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="POLICESTATIC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("Contactno", models.IntegerField(max_length=30)),
                ("Emailid", models.EmailField(max_length=30)),
                ("Map", models.CharField(max_length=30)),
            ],
        ),
    ]
