# Generated by Django 5.0.1 on 2024-02-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0004_blog_helplineno_laws_ngos_policestatic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="Post_date",
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name="helplineno",
            name="Number",
            field=models.CharField(max_length=30),
        ),
    ]
