# Generated by Django 5.0.1 on 2024-02-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0005_alter_blog_post_date_alter_helplineno_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="helplineno",
            old_name="Number",
            new_name="Email",
        ),
        migrations.RenameField(
            model_name="helplineno",
            old_name="State",
            new_name="Regional_Office",
        ),
        migrations.AddField(
            model_name="helplineno",
            name="Address",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="helplineno",
            name="Mobile_No",
            field=models.IntegerField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="helplineno",
            name="Telephone_No",
            field=models.IntegerField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="helplineno",
            name="Name",
            field=models.CharField(max_length=100),
        ),
    ]
