# Generated by Django 5.0.1 on 2024-02-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0006_rename_number_helplineno_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helplineno",
            name="Telephone_No",
            field=models.CharField(max_length=30),
        ),
    ]
