# Generated by Django 5.0.1 on 2024-02-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0007_alter_helplineno_telephone_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helplineno",
            name="Mobile_No",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="policestatic",
            name="Contactno",
            field=models.CharField(max_length=30),
        ),
    ]
