# Generated by Django 5.0.1 on 2024-02-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0008_alter_helplineno_mobile_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lawer",
            name="Emailid",
        ),
        migrations.RemoveField(
            model_name="lawer",
            name="Firm",
        ),
        migrations.RemoveField(
            model_name="lawer",
            name="Map",
        ),
        migrations.AlterField(
            model_name="helplineno",
            name="Address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="helplineno",
            name="Email",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="helplineno",
            name="Regional_Office",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="lawer",
            name="Address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="lawer",
            name="Contactno",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="lawer",
            name="Info",
            field=models.TextField(),
        ),
    ]
