# Generated by Django 5.0.1 on 2024-02-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0009_remove_lawer_emailid_remove_lawer_firm_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="POLICESTATIONS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=30)),
                ("Contactno", models.CharField(max_length=30)),
                ("Emailid", models.CharField(max_length=100)),
                ("Map", models.ImageField(blank=True, upload_to="data")),
            ],
        ),
        migrations.DeleteModel(
            name="POLICESTATIC",
        ),
        migrations.AlterField(
            model_name="laws",
            name="Description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="laws",
            name="Law_category",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="laws",
            name="Name",
            field=models.TextField(),
        ),
    ]
