# Generated by Django 5.0.1 on 2024-02-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0010_policestations_delete_policestatic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Myreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=1000)),
                ("Message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="userregister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=200)),
                ("Password", models.CharField(max_length=300)),
                ("ConfirmPassword", models.CharField(max_length=300)),
                ("Email", models.EmailField(max_length=254)),
            ],
        ),
    ]
