# Generated by Django 5.0.1 on 2024-02-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0011_myreview_userregister"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngos",
            name="Contactno",
            field=models.IntegerField(),
        ),
    ]
