# Generated by Django 5.0.1 on 2024-02-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0012_alter_ngos_contactno"),
    ]

    operations = [
        migrations.CreateModel(
            name="editprofile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="userregister",
            name="Address",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="DateOfBirth",
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="Gender",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="userregister",
            name="Image",
            field=models.ImageField(blank=True, null=True, upload_to="data"),
        ),
        migrations.AddField(
            model_name="userregister",
            name="MobileNumber",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
