# Generated by Django 5.0.1 on 2024-03-30 21:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0013_editprofile_userregister_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_published", models.DateField(blank=True, null=True)),
                ("heading", models.CharField(max_length=1000)),
                ("description", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name="myreview",
            name="Title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userregister",
            name="DateOfBirth",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
