# Generated by Django 5.0.1 on 2024-04-01 21:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0014_alert_alter_myreview_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="Content",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="Post_date",
        ),
        migrations.AddField(
            model_name="blog",
            name="des",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="Title",
            field=models.CharField(max_length=10000),
        ),
    ]
