# Generated by Django 5.0.1 on 2024-04-02 23:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "cyberapp",
            "0015_remove_blog_content_remove_blog_post_date_blog_des_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userregister",
            name="Address",
        ),
    ]
