# Generated by Django 5.0.1 on 2024-04-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0016_remove_userregister_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userregister",
            name="DateOfBirth",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
