# Generated by Django 5.0.1 on 2024-04-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyberapp", "0017_alter_userregister_dateofbirth"),
    ]

    operations = [
        migrations.AddField(
            model_name="myreview",
            name="User",
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
